configs:
  lighthouse:
    threshold:
      accessibility: 90
      best-practices: 90
      performance: 60
      pwa: 70
      seo: 100

  size:
    -
      path: ./build/precache-*.js
      maxSize: 500 B
    -
      path: ./build/static/js/*.chunk.js
      maxSize: 1 MB
    -
      path: ./build/static/js/runtime*.js
      maxSize: 10 KB
    -
      path: ./build/
      maxSize: 18 MB

outputs:
  json: artifacts/results.json

jobs:
  - cra --no-calculate-unused-source
