configs:
  heap-snapshot:
    threshold:
      Documents: 2
      Frames: 1
      Nodes: 750
      RecalcStyleCount: 9
  lighthouse:
    threshold:
      accessibility: 93
      'best-practices': 100
      performance: 70
      pwa: 75
      seo: 100
  size:
    -
      path: ./build/precache-*.js
      maxSize: 500 B
    -
      path: ./build/static/js/*.chunk.js
      maxSize: 1 MB
    -
      path: ./build/static/js/runtime*.js
      maxSize: 10 KB
    -
      path: ./build/
      maxSize: 18 MB

outputs:
  json: artifacts/results.json

jobs:
  - cra --no-calculate-unused-source
