configs:
  heap-snapshot:
    threshold:
      Documents: 6
      Frames: 2
      JSHeapTotalSize: 23356000
      JSHeapUsedSize: 15068000
      Nodes: 800
      RecalcStyleCount: 9
  lighthouse:
    threshold:
      accessibility: 93
      'best-practices': 90
      performance: 50
      pwa: 75
      seo: 100
  size:
    - path: ./build/precache-*.js
      maxSize: 500 B
    - path: ./build/static/js/*.chunk.js
      maxSize: 1 MB
    - path: ./build/static/js/runtime*.js
      maxSize: 10 KB
    - path: ./build/
      maxSize: 18 MB
  unused-source:
    threshold: 0%

outputs:
  html: artifacts/results.html
  json: artifacts/results.json
  markdown: artifacts/results.md

jobs:
  - audit
