aliases:
  - &restore-npm-cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}
  - &restore-webpack-cache
    key: v1-webpackcache-{{ checksum "yarn.lock" }}
  - &restore-dist-cache
    key: v1-dist-{{ .Environment.CIRCLE_SHA1 }}

defaults: &defaults
  working_directory: /home/circleci/repo
  docker:
    - image: circleci/node:10-browsers

version: 2.1
jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Install Node modules
          command: npm i -ci
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  build-pwa:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - restore_cache: *restore-webpack-cache
      - run:
          name: Build Project
          command: npm run build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build
      - save_cache:
          key: v1-webpackcache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/.cache

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run Test TypeScript Compile
          command: npm run check:compile

  gimbal:
    <<: *defaults
    docker:
      - image: moduscreate/gimbal:1.0.2
    steps:
      - checkout
      - restore_cache: *restore-dist-cache
      - run:
          name: Run Gimbal
          command: gimbal
      - store_artifacts:
          path: ./artifacts

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - build-pwa:
          requires:
            - lint
      - gimbal:
          requires:
            - build-pwa
